services:
  maintainarr:
    build: .
    image: local/maintainarr:latest
    container_name: maintainarr
    restart: unless-stopped
    volumes:
      - /mnt/hdd/media-server/data:/data
      - /mnt/hdd/media-server/services/maintainarr:/config
      - /mnt/hdd/media-server/services/radarr/config.xml:/servarr/radarr-config.xml:ro
      - /mnt/hdd/media-server/services/sonarr/config.xml:/servarr/sonarr-config.xml:ro
